"""Initial migration with User, NewsCategory, and NewsArticle models

Revision ID: 54f3b4b7cd83
Revises: 
Create Date: 2026-01-17 00:32:56.625143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f3b4b7cd83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_categories_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_articles_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_title'))
        batch_op.drop_index(batch_op.f('ix_news_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_news_articles_publish_date'))
        batch_op.drop_index(batch_op.f('ix_news_articles_is_published'))
        batch_op.drop_index(batch_op.f('ix_news_articles_is_featured'))

    op.drop_table('news_articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_news_categories_name'))

    op.drop_table('news_categories')
    # ### end Alembic commands ###
