"""Add Fiascha citizen fields to User model

Revision ID: 8cc9c378d8d9
Revises: 54f3b4b7cd83
Create Date: 2026-01-17 00:44:54.609298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc9c378d8d9'
down_revision = '54f3b4b7cd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citizen_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('citizen_rank', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_citizen_id'), ['citizen_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_citizen_id'))
        batch_op.drop_column('citizen_rank')
        batch_op.drop_column('full_name')
        batch_op.drop_column('citizen_id')

    # ### end Alembic commands ###
